image: fpco/stack-build:latest

# If you have dependencies that aren't included in the Dockerfile.
# You might also consider making a new Docker image based on stack-build
# and pushing it to GitLab's registry to save on build time.
before_script:
  - apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
  - apt update -y
  - apt install llvm-8

# https://docs.gitlab.com/ee/ci/yaml/#stages
# jobs of the same stage are executed in parallel
stages:
  - build
  - test

# https://docs.gitlab.com/ee/ci/variables/#using-the-ci-variables-in-your-job-scripts
variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

build:
  # https://docs.gitlab.com/ee/ci/yaml/#cache
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack --no-terminal build

test:
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack --no-terminal test
