name:                carth
version:             0.1.0.0
git:                 https://gitlab.com/JoJoZ/carth
homepage:            https://carth.jo.zone
license:             AGPL-3
author:              "Johan Johansson"
maintainer:          "jo@jo.zone"
copyright:           "2019 Johan Johansson"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at <https://gitlab.com/JoJoZ/carth/blob/master/README.org>

dependencies:
- base
- parsec
- either
- QuickCheck
- containers
- composition
- mtl
- lens
- utility-ht
- llvm-hs-pure == 8.0.0
- llvm-hs == 8.0.0
- llvm-hs-pretty
- filepath
- bytestring
- utf8-string
- composition-extra
- prettyprinter
- process

library:
  source-dirs: src
  ghc-options:
  - -Weverything
  - -Werror
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-import-lists
  - -Wno-missing-exported-signatures
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Wno-name-shadowing
  - -Wno-orphans
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations

executables:
  carth:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Werror
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-missing-import-lists
    - -Wno-missing-exported-signatures
    - -Wno-missing-local-signatures
    - -Wno-monomorphism-restriction
    - -Wno-implicit-prelude
    - -Wno-name-shadowing
    - -Wno-orphans
    - -Wno-missed-specialisations
    - -Wno-all-missed-specialisations
    dependencies:
    - carth

tests:
  carth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carth
    - hspec
    - hspec-discover
