name:                carth
version:             0.0.4.0
git:                 https://github.com/bryal/carth
homepage:            https://carth.jo.zone
license:             AGPL-3.0-or-later
author:              "Johan Johansson"
maintainer:          "jo@jo.zone"
copyright:           "2020 Johan Johansson"

extra-source-files:
- README.org
- CHANGELOG.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bryal/carth#readme>

dependencies:
- base
- megaparsec
- containers
- mtl
- microlens-platform
- llvm-hs-pure
- llvm-hs
- filepath
- directory
- bytestring
- utf8-string
- process
- template-haskell

library:
  source-dirs: src
  extra-libraries:
  - carth_foreign_core
  ghc-options:
  - -Weverything
  - -Werror
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-import-lists
  - -Wno-missing-exported-signatures
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-implicit-prelude
  - -Wno-name-shadowing
  - -Wno-orphans
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unticked-promoted-constructors

executables:
  carth:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Werror
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-missing-import-lists
    - -Wno-missing-exported-signatures
    - -Wno-missing-local-signatures
    - -Wno-monomorphism-restriction
    - -Wno-implicit-prelude
    - -Wno-name-shadowing
    - -Wno-orphans
    - -Wno-missed-specialisations
    - -Wno-all-missed-specialisations
    - -Wno-unticked-promoted-constructors
    dependencies:
    - carth

tests:
  carth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Werror
    - -Wno-safe
    - -Wno-unsafe
    - -Wno-missing-import-lists
    - -Wno-missing-exported-signatures
    - -Wno-missing-export-lists
    - -Wno-missing-local-signatures
    - -Wno-missing-signatures
    - -Wno-monomorphism-restriction
    - -Wno-implicit-prelude
    - -Wno-name-shadowing
    - -Wno-orphans
    - -Wno-missed-specialisations
    - -Wno-all-missed-specialisations
    - -Wno-unticked-promoted-constructors
    dependencies:
    - carth
    - hspec
    - hspec-discover
    - QuickCheck
