name:                carth
version:             0.1.0.0
github:              "bryal/carth"
license:             AGPL-3
author:              "Johan Johansson"
maintainer:          "96.bryal@gmail.com"
copyright:           "2018 Johan Johansson"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bryal/carth#readme>

dependencies:
- base >= 4.7 && < 5
- parsec == 3.1.13.0
- either
- QuickCheck
- containers
- composition

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

  - -fno-warn-name-shadowing
  - -fno-warn-orphans
  - -fno-warn-unused-do-bind

executables:
  carth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carth

tests:
  carth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - carth
    - hspec
    - hspec-discover
